version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/ui"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/apps/client"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/apps/server"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: ""
    schedule:
      interval: "daily"
